id: P8B494823
initial_creation_type: input
source_metadata:
  title: Dzogchen Series
  language: pt
  description: 'The following texts are available as part of our Dzogchen (rdzogs
    chen) or Great Perfection series:'
  volume:
    1b9c1b5ed626417abc67d694dfb85a75:
      title: Advice for Hor Özer
      parent: Advice
    7e98f99e609b4850b537bdac7cd9a0f6:
      title: Advice for Palseng
      parent: Advice
    501736b4672a45ecb1897e4d20cd806e:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    ba25d5de8ff74ab394242e2f2e77c489:
      title: Advice for Garje Khamtrul Rinpoche
      parent: Advice
    a2faddc25fb74974b805d25810c88f09:
      title: Advice on Recognizing the Nature of Mind
      parent: Advice
    4270e3a4322348a4ad6ec0f35be802f5:
      title: 'Advice: Emptying the Three Realms of Existence'
      parent: Advice
    487679312db846d6b6bd4ffa15d5b32f:
      title: An Instruction on the Great Perfection
      parent: Advice
    c4f39be9ec8b4d06aeaa9ab62a04c118:
      title: Brief Dzogchen Instruction
      parent: Advice
    6c580dc4c7884ee3a96ba701564566fa:
      title: Direct Instruction
      parent: Advice
    498f877f22ba49eb860322093688b015:
      title: Summary of the Key Points of Advice on Trekchö
      parent: Advice
    d4d1fb2ec639456a97823a04028eeab3:
      title: Vajra Verses on the Natural State
      parent: Advice
    a8914fbcca274e53b7f2f4b98c8ed4e7:
      title: Advice for a King
      parent: Advice
    9b90dd4db8ab4a858d8ab5c0b02a7071:
      title: A Song of Advice for Gok Zangden
      parent: Advice
    f306479076274952b7171d81cffec37a:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Advice
    6c77bd95dfe1449a84630017e01b2b5b:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    39b49f2819ce413bbf84c6ec20b20982:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    a4429d77764c40509bbeec162b4c68b4:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Advice
    7139d2bc506541dd9c685a813efe42d2:
      title: A Liberating Reminder
      parent: Advice
    e6723e0083c04bbf8c021dd4fa3a10d6:
      title: 'A Mirror Revealing the Crucial Points: Advice on the Ultimate Meaning'
      parent: Advice
    08ce5a0094ec4868b3acee6f1b032097:
      title: 'A Wish-Fulfilling Gem: Guidance on the Meaning of Being at Ease with
        Illusion, A Dzogchen Teaching'
      parent: Advice
    46de98946b064748a2c2aa9dfa642bc8:
      title: 'From ''Finding Comfort and Ease in Meditation'': A Guide to Locations
        for Cultivating Samadhi'
      parent: Advice
    1560069f846b42fca3d1dbbaf78f1006:
      title: 'From ''Finding Comfort and Ease in Meditation'': The Practitioner of
        Meditation'
      parent: Advice
    79fda6642d5c49baa3fb48dc2b765fd7:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Advice
    19dd6a3ea8b64b139eec0fc9f60a35f6:
      title: Pith Instruction on the Three Crucial Statements
      parent: Advice
    2b24e6b265e54489803a90ac94e279f7:
      title: The Essence of Mind
      parent: Advice
    76ca1fa1e97647838c3091dedd2f931a:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Advice
    53c3ecdd8b2a4d519a5ae8dc584d9648:
      title: The Key Points of Trekchö
      parent: Advice
    703cea2db12043a4b549c56e0e41a8ad:
      title: The Nature of Mind
      parent: Advice
    196ed79e229a462f8cd679c5325a88ac:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    3979c4d0de684336b27fafda43cf46d6:
      title: The Pointing-the-Staff Instruction
      parent: Advice
    932f927407714544aa7f4c11df715cc5:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Advice
    f2fdff4e418b483783a5e2f95bd237b7:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Advice
    73a518fbd4744f1fb84be8382582506d:
      title: The Five Wisdoms
      parent: Advice
    b389c55386a24bf988cecdbeed8bf993:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Advice
    2ab6f8a9fb4a4053a0ed2ad488149bd8:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Advice
    8942c311c73345daa4175b5243963b7a:
      title: Advice from the Lips of Tertön Sogyal
      parent: Advice
    c3be544b33ca41a6827b30546f0b5a27:
      title: A Torch to Illuminate Crucial Points of the Path of Meditation
      parent: Advice
    51ab92d444c548ca9221612e5654a467:
      title: The Four Uncommon Samayas of the Great Perfection
      parent: Advice
    7a074942d6db4b1e8d91e0f48e192aa8:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    96d26397ff9b4862aae0936892ace1cd:
      title: From the Oral Tradition of the Lama of Nyarong
      parent: Advice
    c82d5d575758438896993478cca37073:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
    8459bcfb652e48f9b6bf7ce97afbdf69:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      parent: Commentaries
    ddc5f791b0644ca68c264acd16f70952:
      title: 'The Prayer of the Ground, Path & Fruition from the Heart-Essence of
        the Vast Expanse:'
      parent: Commentaries
    d964131e438346b1a00bd4f66bb9650a:
      title: Commentary on Vajra Verses on the Natural State
      parent: Commentaries
    8a54b80f0d7b4d9e832c9f752d003668:
      title: Prayer to the Gurus of the Dzogchen Lineage
      parent: Lineage Prayers
    9f3352bda1c8455589aea15c774d16ca:
      title: A Prayer to Shower Down the Rain of Wisdom
      parent: Lineage Prayers
    8ca78e8eb97f4912a0fcff8538d734e4:
      title: How to Count the Four Permutations of Actual and Basis
      parent: Notes
    956479137efd4f298dbc4146c0a0d1c9:
      title: Commentary on Some Terms from the Great Perfection
      parent: Notes
    d24b9f99fd7144cebdc4fb2ef7295bd0:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      parent: Notes
    022b2f02a08b42d985fc0fb3c67a06d7:
      title: How Liberation and Delusion Develop Out of the Clear Light of the Ground,
        etc.
      parent: Notes
    95fd4086efff402dba80d296bcd583fe:
      title: Notes from the Oral Tradition on Ālaya, Ālaya Consciousness, etc.
      parent: Notes
    7e89a2eeaecc412f831cbc0d9bf3f993:
      title: Dzogchen Aspiration Prayer
      parent: Prayers
    78445dc447c7414ab39b73a3fcf07bac:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    bccba79450e643f6906863fa0955afba:
      title: A Dzogchen Tögal Prayer
      parent: Prayers
    189727e8c926417f82a8e0da9ddd7378:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Prayers
    a035569629004b17a59751ac241d0196:
      title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on
        the Meaning of the Great Perfection'
      parent: Prayers
    04f90f43ad414656b3ad110a07cd425e:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Prayers
    346ae536b14841cc98eec4fc78118e42:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
    ec5cb8e2ac624274aa58023a643fea01:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Prayers
    f93a3632270f49a9acd86ccc05e1912b:
      title: The Song of the Vajra
      parent: Songs
    5ae4740163e54d8faf75dfb5344a3331:
      title: A Song in Six Verses
      parent: Songs
    f6a47ed490454a22af442c398b7968e4:
      title: Song of Experiential Certainty
      parent: Songs
    266c1f1ade38443ebc07357360c1c06e:
      title: Spontaneously Written Song of Experience
      parent: Songs
    d3e1eabfb8af466297fa145329e3964a:
      title: In This Pure Awareness
      parent: Songs
    04d5365848114ca59776b9b8230f35a2:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Songs
    94f9e5f210cb44f393136cd2032f456f:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    80790a77da4c4ac9a5dc0ea300322689:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T03:36:31.999147'
last_modified_at: '2022-03-01T03:36:31.999150'
